In [1]:
#Multivariate feature selection
import numpy
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestRegressor
from numpy import genfromtxt, savetxt
from numpy import mean, concatenate, random
import time
from sklearn.preprocessing import Imputer
from sklearn.metrics import mean_absolute_error
from sklearn.svm import SVR


A = genfromtxt('X_flow.csv', delimiter = ',', dtype = 'double')[1:]
B = genfromtxt('Y.csv' , delimiter = ',', dtype = 'double')[1:]
data = concatenate((A, B), axis = 1)
print(len(data))
print(len(data[0]))
imp = Imputer(missing_values='NaN', strategy='mean', axis=1)
data_set = imp.transform(data)
#=============================================
X = data_set[:,:25]
Y = data_set[:,38]
# feature extraction
start1=time.time()
#model = LogisticRegression()
#model = LinearSVC()
#model = SVR(kernel="linear")
#model = SVC(kernel="linear", C=1)
#model = LinearRegression()
model = Ridge()
rfe = RFE(model, 5)
fit = rfe.fit(X, Y)
end1=time.time()
numpy.set_printoptions(precision=3)
print("preprocessing time is")
print(end1-start1)
#print("Num Features: %d") % fit.n_features_
#print("Selected Features: %s") % fit.support_
#print("Feature Ranking: %s") % fit.ranking_

features = fit.transform(X)
# summarize selected features
print(features)
print(len(features))
print(len(features[0]))
#=============================================
data_set = concatenate((features,data_set[:,38:39]), axis = 1)
random.shuffle(data_set)
print(len(data_set))
print(len(data_set[0]))
training_set = data_set[:25644, 0:5]
target_set =  data_set [:25644, 5]
test_set = data_set [25644:36634, 0:5]
print (len(training_set))
#print (target_set)
print (len(test_set))
start = time.time()
rf = RandomForestRegressor(n_estimators=120, n_jobs = 24)
rf = rf.fit(training_set, target_set)
end = time.time()
print("the training time is")
print(end - start)
y_pred = rf.predict(test_set)
print(y_pred)
print("<<======================================================================================>>")
y_values = data_set[25644:36634, 5]
print(y_values)
MAE = mean_absolute_error(y_values, y_pred)
print(MAE)
m = mean(y_values) 
print(m)
print(MAE/m)

36633
40
preprocessing time is
1.6768925189971924
[[ 27.  26.  24.  25.  20.]
 [ 15.  14.  19.  15.   9.]
 [ 11.  10.  11.  10.   9.]
 ..., 
 [ 15.  12.  17.  15.  15.]
 [ 30.  24.  24.  22.  15.]
 [  0.   0.   0.   0.   4.]]
36633
5
36633
6
25644
10989
the training time is
4.177766799926758
[ 23.879  22.926  21.008 ...,  22.05   20.825  23.033]
<<======================================================================================>>
[ 24.  24.  24. ...,  24.  13.  24.]
3.0506988684
22.0238420238
0.138518014482


In [ ]:
#Multivariate feature selection
# Feature Extraction with Univariate Statistical Tests (Chi-squared for classification)
import numpy
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge

# load data
#KV_periodic/X_cluster.csv
from sklearn.ensemble import RandomForestRegressor
from numpy import genfromtxt, savetxt
from numpy import mean, concatenate, random
import time
from sklearn.preprocessing import Imputer
from sklearn.metrics import mean_absolute_error


A = genfromtxt('X_cluster.csv', delimiter = ',', dtype = 'double')[1:]
B = genfromtxt('Y1.csv' , delimiter = ',', dtype = 'double')[1:]
data = concatenate((A, B), axis = 1)
print(len(data))
print(len(data[0]))
imp = Imputer(missing_values='NaN', strategy='mean', axis=1)
data_set = imp.transform(data)
#=============================================
X = data_set[:,:10374]
Y = data_set[:,10376]
print(Y)
# feature extraction
start1=time.time()
model = LinearRegression(n_jobs=24)
#model = Ridge()
rfe = RFE(model, 5)
fit = rfe.fit(X, Y)
end1=time.time()
numpy.set_printoptions(precision=3)
print("preprocessing time is")
print(end1-start1)
#print("Num Features: %d") % fit.n_features_
#print("Selected Features: %s") % fit.support_
#print("Feature Ranking: %s") % fit.ranking_

features = fit.transform(X)
# summarize selected features
print(features)
print(len(features))
print(len(features[0]))
#=============================================
data_set = concatenate((features,data_set[:,10376:10377]), axis = 1)
random.shuffle(data_set)
print(len(data_set))
print(len(data_set[0]))
training_set = data_set[:20274, :5]
target_set =  data_set [:20274, 5]
test_set = data_set [20274:28964, :5]
print (len(training_set))
#print (target_set)
print (len(test_set))
start = time.time()
rf = RandomForestRegressor(n_estimators=120, n_jobs = 24)
rf = rf.fit(training_set, target_set)
end = time.time()
print(end - start)
y_pred = rf.predict(test_set)
print(y_pred)
print("<<======================================================================================>>")
y_values = data_set[20274:28964, 5]
print(y_values)
MAE = mean_absolute_error(y_values, y_pred)
print(MAE)
m = mean(y_values) 
print(m)
print(MAE/m)